# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d8a4cde0029506c9b377d803a3eac612e35497b6eb9f42c207f947b864518a836c6fd19de3be33d9800329e7b82ae2dff069a046056dcb1334e9b6f2c07a550

test:
  secret_key_base: 18c57c76eafee716d2fde80dee082ddfc3ec31a7e23127d14f98e45b1216c4d791fa1f3e24948ec82b08b164bae502481d7a7d7966339c906d6209f28a59e235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
